### ISSUE TITLE
[ilp-core] Add Unlimited Strength Encryption Policy Files Note in README

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#18]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sappenin](https://github.com/sappenin)**
_Wednesday Jul 26, 2017 at 15:44 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/62_

----

In order for this project to compile, a user will need to install the [Java JCE Unlimited Strength](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) encryption policies from Oracle. 

For example, the main problem building the project in #60 was probably due to not having this installed.

We should update the README to list this as a project dependency.

**Comment by nathanawmk** [comment]
hi @hyperledger-quilt @sappenin 

I had this issue too. 

I'm interested in working on this issue. I'll start working on this today and will put a WIP PR.

Thank You.

Regards,

Nathan Aw

**Comment by sappenin** [comment]
Hi @nathanawmk sounds great, thanks!

**Comment by nathanawmk** [comment]
Hi @sappenin 

I have added Unlimited Strength Encryption Policy Files Note in README. 

I went a step further to include symptoms that I encountered because of this and shared detailed resolution steps. I created a pull request. https://github.com/hyperledger/quilt/pull/69 

Please review my edits and merge this pull request!

Thank you! :) 

Nathan Aw

**Comment by sappenin** [comment]
This is fixed by #112.
