### ISSUE TITLE
[ilp-core] Restrict allowed chars in headers for PSK

### ISSUE THREAD

**Issue by hyperledger-quilt** [hyperledger/quilt#22]
<a href="https://github.com/adrianhopebailie"><img src="https://avatars2.githubusercontent.com/u/49902?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Monday Aug 07, 2017 at 14:17 GMT_
_Originally opened as https://github.com/interledger/java-ilp-core/issues/69_

----

See https://github.com/interledger/rfcs/pull/257 for context

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/controlsurface"><img src="https://avatars1.githubusercontent.com/u/32676654?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [controlsurface](https://github.com/controlsurface)**
_Monday Oct 23, 2017 at 21:54 GMT_

----

@sappenin , all, am planning on taking this one on next.

**Comment by hyperledger-quilt** [comment]
<a href="https://github.com/sappenin"><img src="https://avatars1.githubusercontent.com/u/323659?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sappenin](https://github.com/sappenin)**
_Tuesday Oct 24, 2017 at 00:41 GMT_

----

Sounds good - although you’ll probably want to work off the Hyperledger version now - we’re moving the project under that governance structure - https://github.com/hyperledger/quilt

**Comment by controlsurface** [comment]
I would appreciate some input on this one.  I have found that while it is easy to control the characters allowed while encoding, there are some cases for decoding that are not possible to control.

An invalid private header of `answer: But we control these\n machines; they don't control us!` is detectable because the value portion does not contain a colon.  The '\n' results in the code creating a private header of `answer -> But we control these` followed by a new line of `machines; they don't control us!` which is detectable as an invalid header.

 However, if the value does contain a colon, `answer: But we control these\nmachines: they don't control us!`, then we end up with two private headers `answer -> But we control these` and `machines -> they don't control us!` which ends up being valid.  Another example would be `answer: But we control these\n{\"oracle\":\"candy\", \"forseen\":true}"`, in which case we end up with valid headers of `answer -> But we control these` and `{\"oracle\" -> \"candy\", \"forseen\":true}"`

To detect the latter example, we could add a restriction on the characters allowed in the key portion of a header (no curly braces for example).  However, from a decoding perspective, if a colon is created in the value portion, a nefarious encoder could could effectively inject a header or payload data in the value portion of a header.  Thoughts ?

**Comment by adrianhopebailie** [comment]
@controlsurface: without providing an answer I hope the following is helpful. The PSK headers are modeled on HTTP headers so I assume there are some good examples of HTTP header decoders out there that have solved this problem.

**Comment by sappenin** [comment]
So, I'm wondering if we're pursuing this in the wrong direction -- seems like picking out various illegal characters is not the best approach here.

Could we instead specify a modified BNF from [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2.6) that removes `VCHAR` as well as `comments` and `quoted-strings`? Something like:

```
field-name = token

token = 1*tchar

tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
```

If we did that, then we could use a REGEX to enforce valid characters in the header line (back-slash octet would not be allowed).

**Comment by controlsurface** [comment]
@sappenin Your suggestion makes good sense.  I will update the code and repush.

**Comment by controlsurface** [comment]
@sappenin Looking into this, it appears that we would need to expand the list of acceptable characters.  There are several unit tests elsewhere in ilp-core that do not pass with the new implementation.  A more complete list that allows all unit tests to pass include: ";" / "," / ":" / " " / "?" .  We could eliminate the question mark "?", as the tests failing due to this one do not appear to be real headers (e.g., What is the answer?).  Thoughts ?

Examples taken from Unit tests that do not pass are:

[ERROR] test(org.interledger.ipr.InterledgerPaymentRequestEndToEndTest)  Time elapsed: 5.135 s  <<< ERROR!
org.interledger.codecs.CodecException: The value of the PskMessage header 'Expires-At' (2017-11-16T07:58:20.582-08:00) contains an illegal character **(The list does not contain ':')**

[ERROR] test(org.interledger.ipr.InterledgerPaymentRequestEndToEndTest)  Time elapsed: 5.135 s  <<< ERROR!
org.interledger.codecs.CodecException: The value of the PskMessage header 'Encryption' (aes-256-gcm -BnF608uR7y3xY730dp9rQ) contains an illegal character This is not allowed.
	at org.interledger.ipr.InterledgerPaymentRequestEndToEndTest.test(InterledgerPaymentRequestEndToEndTest.java:104) **(The list does not contain spaces)**

[ERROR] testWriteRead[0](org.interledger.codecs.oer.psk.InterledgerPaymentWithPskCodecTests)  Time elapsed: 0.012 s  <<< ERROR!
org.interledger.codecs.CodecException: The value of the PskMessage header 'question' (What is the answer?) contains an illegal character This is not allowed.
	at org.interledger.codecs.oer.psk.InterledgerPaymentWithPskCodecTests.testWriteRead(InterledgerPaymentWithPskCodecTests.java:131) **(The list does not contain '?')**

**Comment by sappenin** [comment]
My read of the definition of `tchar` in the BNF of [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2.6), is that `?` is a delimiter, and thus not allowed in the header value. If that's correct, I think we should exclude it.

However, [this post](http://www.bizcoder.com/everything-you-need-to-know-about-http-header-syntax-but-were-afraid-to-ask) is pretty informative when thinking about http header parsing, and contains some discussion about headers that contain multiple values. I wonder if we should consider this in our parser? @controlsurface Are there unit tests around this? @adrianhopebailie Do we even want to allow for this in PSK?

FWIW, there's a table at the bottom of that post that visually shows which characters are valid `tchars`.

@adrianhopebailie What do you think about all this? We're sort of arbitrarily inventing a standard here as a subset of RFC7230, so we should probably think about this more.

Last but not least, @controlsurface be sure to read [section 3.2.3](https://tools.ietf.org/html/rfc7230#section-3.2.3) in RFC7230 about whitespace. For example, a header line can include whitespace, like this:

`header-field   = field-name ":" OWS field-value OWS`

**Comment by sappenin** [comment]
Perhaps we should use an existing library, like [BasicHeaderValueParser](https://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/message/BasicHeaderValueParser.html)?

**Comment by adrianhopebailie** [comment]
PSK has been superseded by STREAM
