### ISSUE TITLE
Should this unused repo be deleted?

### ISSUE THREAD

**Issue by ryjones** [hyperledger/quilt#264]
https://github.com/hyperledger/quilt-crypto-conditions was created in 2017 and was never used. May I delete it?

**Comment by sappenin** [comment]
Hey @ryjones - you are correct, that project never really went anywhere because we decided that the full suite of crypto-conditions aren't necessary in Interledger. 

Feel free to delete that repo!

(For anyone reading along at home wanting to know where a Java implementation of CryptoConditions can be found, please see: https://github.com/ripple/crypto-conditions)
