### ISSUE TITLE
Introduce a Time-based backoff in STREAM Sender

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#289]
The current STREAM sender handles `T04` and `F08` rejection error codes, but it does not do anything with other temporary or final error codes. The only recourse here for users of the StreamSender is to specify a timeout when calling `sendMoney`, but the `soldierOn` run-loop should be a bit smarter when it hasn't timed-out, but _is_ encountering a lot of `T` family errors. This is known as a time-based back-off.

See examples from the JS Stream implementation: 

* https://github.com/interledgerjs/ilp-protocol-stream/blob/master/src/connection.ts#L1481

**Comment by theotherian** [comment]
An attempt was made on this in #394 but ultimately abandoned due to some of the nuance around performing retries and the growing scope of `SimpleStreamSender`.

- the `PreparePacket` needs to be recreates for retries since the `expiresAt` will be an issue as the exponential backoff interval increases.
- in the initial implementation no effort was made to coordinate retries in a way that accounted for all active threads, meaning that rejects happened in two different places. A sender that is trying to account for exponential backoff should have some mechanism for accounting for this. In the previous attempt the logic was encapsulated in another time but this led to some confusion around separation of concerns.
- we need to make sure we add jitter to whatever solution we choose to avoid getting into a pattern of resending all of the same packets at the same time and overwhelming a server with spotty availability.
- The `T04` error shouldn't create this type of exponentially backed-off retry

**Comment by sappenin** [comment]
More context here since some time has past.

> the PreparePacket needs to be recreates for retries since the expiresAt will be an issue as the exponential backoff interval increases.
This is no longer an issue thanks to #433

**Comment by sappenin** [comment]
StreamSender has been deprecated in-favor of [ILP Pay](https://github.com/hyperledger/quilt/tree/df/ilp-pay) functionality. Closing this.
