### ISSUE TITLE
Implement ExchangeRate Mechanism for StreamSender

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#291]
We talked about doing the following to support ExchangeRates in the `StreamSender`:

**Problem**
Currently, the sender doesn't account for exchange rates. While this is currently being addressed as part of #261, we need to update the sender to do the following:

* Open the STREAM connection with a StreamPacket containing the following: A 0 amount, a ConnectionNewAddressFrame, and a StreamMoneyFrame (this is happening, but should maybe be pulled out into its own function called openMoneyStream.
* Once the connection asset details are received, the STREAM can then start using the CongestionController to send N number of packets in parallel with a particular packet amount.
* Need MinimumAcceptableAmountGuard interface with a "Always Return 1" basic implementation.
* `boolean isAcceptable(BigInteger sourceAmount, Denomination sourceDenomination, BigInteger reportedAmountDelivered, Denomination reportedAmountDenomination, maxSlippage);
* Add overloaded sendMoney that accepts an instance MinimumAcceptableAmountGuard. Other method has no MinimumAcceptableAmountGuard and calls the other sendMoney with a default implementation that always true.

**However**, before we implement this design, let's understand what the [Javascript implementation is doing here](https://github.com/interledgerjs/ilp-protocol-stream/blob/master/src/connection.ts#L1160).

**Comment by sappenin** [comment]
We need to make the StreamSender aware of its Link Asset type and scale (see `Denomination`).

**Comment by theotherian** [comment]
This ticket as a bunch of moving parts to it that ended up being identified but need to be documented (and have their details sorted out) for an eventual implementation.

- **The MinimumAcceptableAmountGuard interface needs methods to indicate if it accepts specific asset codes.** These would need to be checked before attempting to apply a guard to a transaction, otherwise the result could be wildly inaccurate. 
- **As of right now, it seems the most appropriate place to add the guard is `StreamSender.sendMoney`.** The reason for this is that constraining the guard to the constructor of an implementation of `StreamSender` creates a burden on preemptively passing a guard capable of servicing all calls to `sendMoney` for the lifetime of the sender.
- **The `SimpleStreamSender` needs to parse the `ConnectionAssetDetails` frame returned from the receiver (all `StreamSender` implementations have to).** Without capturing this information, we have no idea whether or not a guard even works properly for a given `sendMoney` invocation.
- **We don't know what the correct failure model is.** Since we're adding some validation constraint via the guard, we need to be able to fail when that constraint is violated, but as of now there are some unanswered questions on how to accomplish this.
- **At this point in time, we're punting this to 1.1 because these are nontrivial problems.** This does mean that connectors can possibly steal money while a sender tries to satisfied the amount to deliver to the receiver. 

Considerations for a failure model for exchange rates/transaction fees:
- **Failing fast isn't inherently desirable so we need some kind of tolerance factor.** Since you need to examine how much is delivered, you might fail prematurely if the connector took a larger chunk out of the first packet but not from others, or if there was some other failure. One means to do this would be to have some kind of semantics around tolerance of a running average, but that also has problems.
- **We can't rely on aggregates for fulfills received/amount delivered for averages.** As of when this comment was written, when we handle a fulfill, we're tracking the total amount delivered as well as the number of packets sent as two different atomic references. These are unreliable though because an unknown number of threads could be processing a stream at any given time and have interleaving invocations of incrementing the number of packets or delivered amount in such a way that we cannot ever assume an average calculated to be accurate. Instead, we should maintain a concurrent collection that stores some representation of a transaction and reduce to an average to check, but sadly it's not as cut and dry as this because you still could fail too quickly. We probably need to examine the amount to send and the prepare amounts to figure out if we've reached an appropriate place to start measuring this value. Does this end up being some percentage of the total?
- **Storing representations of each transaction has the added upside of returning a more meaningful `SendMoneyResult`.** We already know that we can experience failures somewhere in the middle of a stream, and right now we do a poor job of providing context of the failure which seems particularly bad seeing that some amount of money has already changed hands. By providing the series of transactions for the `sendMoney` call, we can provide callers inside as to where and how the request failed.

**Comment by sappenin** [comment]
Fixed via #327
