### ISSUE TITLE
SimpleStreamSender ignores 4XX errors and retries (and fails) repeatedly

### ISSUE THREAD

**Issue by nhartner** [hyperledger/quilt#370]
When SimpleStreamSender.sendMoney attempts to send a payment and gets a 4XX error (e.g. 401 for bad password), it repeatedly retries sending packets until it eventually times out. Instead, it should abort since 4XX are not retryable.

**Comment by sappenin** [comment]
From Java Community call: 

* `4xx`: Abort immediately. Return a`SendMoneyResult` with 0 packets and a boolean because it's possible we get a 4xx error in the middle of a stream. Consider adding the error message for debugging. 
* For `5xx` errors there should be a retry limit in addition to the exponential back-off. Need to consider not making the `numRetries` lower than what would make the exponential backoff moot. No matter what `numRetries` is we should always just use exponential backoff, even if it's unused.

**Comment by sappenin** [comment]
This ticket handles 4xx HTTP codes. See https://github.com/hyperledger/quilt/issues/289 for the remaining work to address 5xx error codes (maybe).
