### ISSUE TITLE
Make soldierOn Run-loop's "sleep time" configurable

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#406]
At a minimum, this value should be configurable via an env property, e.g., 500ms.

Note that per @theotherian choosing a longer sleep time probably means we should have longer payment timeout because a longer sleep time increases the chances of hitting the upper time-bound of the payment (i.e., the payment timeout)

**Comment by sappenin** [comment]
Per more recent conversation, we should consider (instead or in addition) just reducing this value to 5ms or something very small. The use-case is when 20 packets need to be sent out, they will be sent sequentially every 100ms, which means that ramp-up will take 20 * 100ms, or 2s.

**Comment by nkramer44** [comment]
Since `SimpleStreamSender` and `SendMoneyAggregator` are not Spring managed beans, configuring this via an application.yml file or another env file gets a bit ugly.  

Would it make more sense to configure this in the `SendMoneyAggregator` constructor (by passing the value through `SimpleStreamSender.sendMoney()`? Any STREAM sender can then configure the value however they want.
