### ISSUE TITLE
[ilp-core] Enforce Regexes from RFC-15

### ISSUE THREAD

**Issue by sappenin** [hyperledger/quilt#57]
From [RFC-0015](https://github.com/interledger/rfcs/blob/master/0015-ilp-addresses/0015-ilp-addresses.md#address-requirements)

>  5.) Destination addresses [...] MUST contain at least two segments after the allocation scheme prefix.

Currently, `InterledgerAddress.java` doesn't enforce that a destination address have at least 2 segements (i.e., `g.foo` is allowed in the `InterledgerAddress` implementation, but should not be).

We should update `#isValidInterledgerAddress` to utlilize a different regex depending on whether or not the String ends with a period [.]. Additionally, we might consider improving the error output instead of just saying, "reference ILP-RFC-15."

**Comment by pascalav** [comment]
To check for proper understanding:
* `final InterledgerAddress destAddr = InterledgerAddress.of("g.segment0");` provides a valid destination address in the current impl, but it should not (i.e. in term of number of segments, `g.segment0.segment1` should be the minimal valid destination address)
* On the address prefix side, any of `g.`, `g.segment0.`, `g.segment0.segment1.`, or a greater segments count, is both valid in specifications as well as in the current impl.


While first trying to update the `InterledgerAddress#isValid(String)` internals to enforce 2+ segments for a destinations address, and while updating tests accordingly, I met a deeper impact: `InterledgerAddress#of(String)`, `InterledgerAddress#with(String)` and `InterledgerAddress#getParentPrefix()` do atomically make use of `InterledgerAddress#isValid(String)`.

This has the following consequences:
* `final InterledgerAddress destAddr = InterledgerAddress.of("g").with("segment0").with("segment1"); // destAddr.getValue() is "g.segment0.segment1" currently. But this would now fail as soon as the "g" destination address creation is attempted on the way down to "g.segment0.segment1"`
* `final InterledgerAddress addrPrefix = InterledgerAddress.of("g.segment0.").getParentPrefix(); // addrPrefix.getValue() is "g." currently. But this would now fail as soon as the "g.segment0" destination address creation is attempted on the way up to "g."`

As a consequence, `InterledgerAddress#isValid(String)` - which is a complete validation of an entire address prefix or destination address - should only be performed when finalizing the IL-address instance (i.e. when invoking the `build` method of the below design proposal)?

For instance:
* `final InterledgerAddress destAddr = InterledgerAddress.of("g").with("segment0").with("segment1").build(); // "g.segment0.segment1", once fully prepared, will validate`
* `final InterledgerAddress addrPrefix = InterledgerAddress.of("g.segment0.").getParentPrefix().build(); // "g.", once fully prepared, will validate`

Explained differently, the refactoring would be to make `of()`, `with()` and `getParentPrefix()` return the non-validating `InterledgerAddressBuilder`, rather than the final `InterledgerAddress`. Does it sound right?

**Comment by sappenin** [comment]
Hi @pascalav, thanks for looking into this, and for your detailed analysis.

First, I don't think we want to change any of the logic around when `isValid` is called, primarily because the existing `of` and `with` methods have a specific contract, which always returns a valid `InterledgerAddress`. 

Here's a summary of the current naming conventions:

*  `Interface.of()` methods are like a constructor, whereby you supply all of the required fields to construct an object, and you get a fully-constructed, valid, immutable object back (typically a static-method on the Interface).
* `Interface.from()` methods are like a factory-method, whereby you supply some "raw materials" that can be used to derive everything necessary to call `.of()` (typically a static-method on the Interface).
* `Interface.with()` methods are called on an already-constructed object, append some information or data, and return a a fully-constructed, valid, immutable object (typically a non-static or default method on the Interface or abstract implementation of an interface). Note that most interfaces in Quilt do not have a "with" method, because most objects are not appendable in the way `InterledgerAddress` is.
* `Interface.builder()` methods return an instance of an immutables-project-generated builder that can be used to mutate data before actual construction. For example, `InterledgerAddressBuilder`.
* `*Builder.from()`: This has a specific meaning in immutables-project-generated builders. See [here](http://immutables.github.io/immutable.html#builder). 

With that in mind, `InterledgerAddress#of` is  meant to function more like a constructor, and _not_ like a builder. In other words, when you call "of", you will receive a complete, fully-valid `InterledgerAddress`. Likewise, the contract for `InterledgerAddress#with` will always start with a valid `InterledgerAddress` and result in a new ILP address with an additional suffix.

Thus, in order to accomplish something closer to the builder-pattern that you identified above (where callers can append portions of an ILP address before actual construction) we have several options:

1. Do nothing. Force callers to construct their ILP address as a String before calling `InterledgerAddress#of`.  
1. Extend the builder generated by Immutables to support this functionality, and then just have developers call `InterledgerAddress#builder`, and use that thing with the new "just append a part of your ILP address" extension method (Unfortunately, I don't think [Immutables](immutables.github.io) supports this in the builder out of the box, but it might worth investigating. If you can't easily customize the generated builders, perhaps it would be worth logging an enhancement in the immutables project).
1. Define our own custom builder that extends the Immutables-generated builder, and is then returned from the static method `InterledgerAddress#builder`.

Overall, I haven't run into a case where I've wanted to gradually assemble an ILP address using the `InterledgerAddress` or `InterledgerAddressBuilder` classes. Instead, a much more common use-case I've encountered is where I have an ILP prefix String (already assembled) that might look like, `g.us.foo.`, and I need to append an account to it (e.g., "myaccount"), so I will often only be doing this:

```
// prefix is an already-assembled ILP address containing "g.us.foo."
void doSomething(InterledgerAddress prefix){
   InterledgerAddress myAccount = ilpAddress.with("myaccount");
   // ... 
}
```

With all that said, I vote for Option 1 above, since I've never encountered a use-case for option 2 or 3 and it's not clear if Option 2 is even possible.

Thoughts?

**Comment by pascalav** [comment]
Hi @sappenin :) Those are good insights regarding naming conventions for the project interfaces, and regarding the integrity constraints for an `InterledgerAddress` instance: thanks.

Since each `InterledgerAddress` instance validity is enforced from construction, and that the `Interface.with()` method aims at assembling 2 real-world instances into a new one, rather than virtually building-up a single new real-world instance in stages: option 1 indeed seems the most suitable.
