### ISSUE TITLE
Problem in tests classes

### ISSUE THREAD

**Issue by jcatino** [hyperledger/quilt#68]
Having problems compiling ilp-core I commented some lines to run the test classes and build packages.

Classes are:
InterledgerErrorOerCodecTests (lines 122 and 137)
IlqpCodecTests (line 95(

(line like: assertThat(error, is(packet)); )

I had to comment this line to run the test. Is any problem with that ?

I'm using Eclipse, compiling with java 9.01 with Maven 3.5.2

**Comment by pascalav** [comment]
@jcatino 

Raw maven build is ok.

About `eclipse`, that's because contents of `<ilp-core_basedir/target/generated-sources/annotations` are not on the eclipse's `ilp-core` project `Java build path` by default (`eclipse` only adds what is in `/src/<main|test>/java`). Add it (through the eclipse's project `properties`). The internal build of `eclipse` then completes properly.

I guess POMs did not want to be IDE-dependent, by declaring a `m2eclipse` `connector` goal for `eclipse`. Such goal would auto add what previously done manually.
